# Generated by Django 4.1.5 on 2023-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.IntegerField(default=5, verbose_name='Yıldız'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.FloatField(default=0, verbose_name='Ürün Puanı'),
        ),
    ]
