# Generated by Django 4.1.5 on 2023-04-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_alter_comment_star_alter_product_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='renk',
            new_name='colors',
        ),
    ]
